name: Build and Package

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    strategy:
      matrix:
        platform: [ ubuntu-latest, windows-latest ]
        include:
          - platform: ubuntu-latest
            arch: amd64
          - platform: ubuntu-latest
            arch: arm64
          - platform: windows-latest
            arch: amd64

    runs-on: ${{ matrix.platform }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python 3.11
        uses: actions/setup-python@v4
        with:
          python-version: 3.11.9

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
          if [ -f Pipfile ]; then pip install pipenv && pipenv install --dev; fi

      - name: Run tests
        run: |
          if [ -f manage.py ]; then python manage.py test; fi

      - name: Build package
        run: |
          python setup.py sdist bdist_wheel

      - name: Archive build artifacts
        if: success()
        uses: actions/upload-artifact@v3
        with:
          name: package-${{ matrix.platform }}-${{ matrix.arch }}
          path: dist/*
