name: Build and Package

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    strategy:
      matrix:
        platform: [ ubuntu-latest, windows-latest, macos-latest ]
        include:
          - platform: ubuntu-latest
            arch: amd64
          - platform: macos-latest
            arch: arm64
          - platform: windows-latest
            arch: amd64

    runs-on: ${{ matrix.platform }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python 3.11
        uses: actions/setup-python@v4
        with:
          python-version: 3.11.9

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Install PyInstaller
        run: |
          pip install pyinstaller==5.13.2

      - name: Build package on Linux
        if: runner.os == 'Linux'
        run: |
          pyinstaller --onefile manage.py

      - name: Build package on Windows
        if: runner.os == 'Windows'
        run: |
          pyinstaller --onefile --windowed manage.py

      - name: Archive build artifacts
        if: success()
        uses: actions/upload-artifact@v3
        with:
          name: package-${{ matrix.platform }}-${{ matrix.arch }}
          path: dist/*
